name:                Groningen
version:             0.1.0.0

default-extensions:
- BangPatterns
- ConstraintKinds
- DefaultSignatures
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers
- safe
- lens
- hashable
- unordered-containers
- constraints
- singletons
- vector
- extensible

library:
  source-dirs: src

executables:
  tmp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - Groningen

