name:                Groningen
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers
- safe
- lens


library:
  source-dirs: src

executables:
  tmp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Groningen

